#if !canImport(ObjectiveC)
import XCTest

extension XPKitTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__XPKitTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(XPKitTests.__allTests__XPKitTests),
    ]
}
#endif
